NO_JIRA: customisable text style in text input field
warp-ds/warp-android pull request #42
Opened 2024-05-14 11:44 UTC by IrynaMartynchuk

In TJT and I saw in some other places sometimes we use `title1` or `title2` text style instead of `body` that now is default and there is no option to have other text style. So I added another parameter `textStyle` to be able to use some other text style in input fields.

2024-05-16 11:52 UTC, julbar requested changes

2024-05-16 12:26 UTC, IrynaMartynchuk commented on warp/src/main/java/com/schibsted/nmp/warp/components/WarpTextField.kt
> +    textStyle: TextStyle = typography.body,
Oh, yeah, forgot about legacy

2024-05-21 08:04 UTC, IrynaMartynchuk commented on warp/src/main/java/com/schibsted/nmp/warp/components/legacy/WarpTextFieldView.kt
> +            val styleInt = getInteger(R.styleable.WarpText_warpTextStyle, 8)
Copy paste error, forgot to change it, I'll fix it

2024-05-21 08:05 UTC, IrynaMartynchuk commented on warp/src/main/java/com/schibsted/nmp/warp/components/WarpTextField.kt
> +    textStyle: TextStyle = typography.body,
Yes, I can change it, that's probably just old habit of using TextStyle

2024-05-21 12:37 UTC, julbar approved these changes

2024-05-21 13:34 UTC, merged