Add checkbox component
warp-ds/warp-android pull request #50
Opened 2024-06-13 14:33 UTC by hang-do-minh

Added implementation for the checkbox component.

<img src="https://github.com/warp-ds/warp-android/assets/103035324/82890296-6b0c-4cd3-924f-f5f4c9120236" width="300" />
<img src="https://github.com/warp-ds/warp-android/assets/103035324/512fd6bc-eb4f-4b81-89be-1d7c7c68d848" width="300" />

2024-06-17 13:18 UTC, julbar commented on warp/src/main/java/com/schibsted/nmp/warp/components/WarpCheckbox.kt
> +    onCheckedChange: ((Boolean) -> Unit)?,
Should this really be optional?

2024-06-17 15:02 UTC, julbar requested changes
We have support for paparazzi now, so would be great to have some screenshot tests aswell. Otherwise looks very nice! Good job!

2024-06-17 15:22 UTC, julbar commented
There is also the Indeterminate mode thats missing.

2024-06-17 15:23 UTC, julbar commented
The disabled checkbox should not be possible to toggle on/off

2024-06-17 15:25 UTC, julbar commented on warp/src/main/java/com/schibsted/nmp/warp/components/WarpCheckbox.kt
> +    onCheckedChange: ((Boolean) -> Unit)?,
Maybe we dont have to require it, but we should give it a default value so that we can define it without empty function params

2024-06-18 08:13 UTC, hang-do-minh commented
> The Checkmark should be more bold. We have support for paparazzi now, so would be great to have some screenshot tests aswell. Otherwise looks very nice! Good job!

I used the default material checkmark icon, but I will look into making it more bold.

2024-06-18 08:16 UTC, julbar requested changes

2024-06-18 08:16 UTC, julbar commented on snapshot/src/test/java/com/schibsted/snapshot/WarpComponentsTest.kt
> +    @Test
It would be better to have the checkbox tests in a separate class/file. Also please include all the different states and styles of the checkbox

2024-08-06 14:24 UTC, julbar approved these changes
Looks really good! Just some old paparazzi screenshots that should be removed, thats all. Big thanks and great work!

2024-08-06 14:24 UTC, julbar commented on snapshot/src/test/snapshots/tori/images/com.schibsted.snapshot_SnapshotTest_warp checkbox[Tori,NOTNIGHT].png
Remove :)

2024-08-06 14:24 UTC, julbar commented on snapshot/src/test/snapshots/tori/images/com.schibsted.snapshot_SnapshotTest_warp checkbox[Tori,NIGHT].png
Remove :)

2024-08-06 14:24 UTC, julbar commented on snapshot/src/test/snapshots/finn/images/com.schibsted.snapshot_SnapshotTest_warp checkbox[Finn,NIGHT].png
Remove :)

2024-08-06 14:24 UTC, julbar commented on snapshot/src/test/snapshots/finn/images/com.schibsted.snapshot_SnapshotTest_warp checkbox[Finn,NOTNIGHT].png
Remove :)

2024-08-07 12:15 UTC, merged